import { JsonLd, Link, PetActions, PetBreadcrumb, PetProductCard, PetShell, QuotationChecklist } from "../pet-travel-components";
import { collectionFaqs, petCategories, petCollectionUrl, petProducts, petSiteUrl } from "../pet-travel-data";

const title = "Custom Pet Travel Bag Manufacturer | Cappuccino Bag";
const description = "OEM and ODM pet carriers, travel organizers, backpacks and walking accessories developed for brands, retailers and distributors.";
export const metadata = { title, description, alternates: { canonical: `${petSiteUrl}${petCollectionUrl}` }, openGraph: { title, description, url: `${petSiteUrl}${petCollectionUrl}`, type: "website", images: [{ url: `${petSiteUrl}/assets/cappuccino-outdoor-bag-factory-workshop.jpg`, width: 1600, height: 900, alt: "Cappuccino Bag factory workshop supporting custom pet travel bag development" }] }, twitter: { card: "summary_large_image", title, description, images: ["/assets/cappuccino-outdoor-bag-factory-workshop.jpg"] }, robots: { index: true, follow: true } };

const highlights = ["OEM / ODM Development", "Custom Materials and Colors", "Recycled Fabric Options", "Private Label Packaging", "Sampling and Bulk Production", "Export Manufacturing Support"];
const reasons = [["Functional-bag experience", "Pet travel is developed as part of Cappuccino Bag's wider outdoor, sports, travel and functional bag capability."], ["Sample-led decisions", "Dimensions, ventilation, structure, carry, cleaning and packaging are reviewed through physical samples."], ["Private-label coordination", "Materials, trims, logos, labels, retail packs and carton marks can be developed as one range."], ["Claim control", "Product and material language is matched to project evidence; no airline approval or safety certification is assumed."]];
const materials = [["Body fabrics", "Polyester and nylon Oxford, ripstop, canvas, coated textiles and documented recycled options"], ["Ventilation", "Abrasion-resistant mesh, spacer mesh and covered ventilation constructions"], ["Structure", "Foam, PE board, wrapped base panels and removable reinforcement"], ["Trims", "Webbing, zippers, hooks, buckles, feet, labels and vegan-leather trim options"], ["Lining", "Polyester, recycled polyester, wipe-clean coated zones and removable washable components"], ["Packaging", "Reduced-plastic polybags, paper wraps, hangtags, inserts, retail cartons and export marks"]];
const process = ["Buyer brief and quotation review", "Material and component sourcing", "Pattern and technical development", "Prototype sample", "Revision and approval", "Pre-production confirmation", "Bulk production and in-line checks", "Final inspection and export packing"];
const useCases = ["Air and rail travel", "Urban walking and transfer", "Car and weekend travel", "Hiking and outdoor carry", "Feeding and supply organization", "Training and daily walking", "Private-label retail programs", "Coordinated sustainable collections"];
const schemas = [{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${petSiteUrl}/` }, { "@type": "ListItem", position: 2, name: "Pet Travel Bags", item: `${petSiteUrl}${petCollectionUrl}` }] }, { "@context": "https://schema.org", "@type": "CollectionPage", name: "Custom Pet Travel Bag Manufacturer", description, url: `${petSiteUrl}${petCollectionUrl}`, mainEntity: { "@type": "ItemList", numberOfItems: petProducts.length, itemListElement: petProducts.map((product, index) => ({ "@type": "ListItem", position: index + 1, name: product.name, url: `${petSiteUrl}${product.href}` })) } }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: collectionFaqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }];

export default function PetTravelCollectionPage() {
  return <>{schemas.map((schema) => <JsonLd key={schema["@type"]} value={schema} />)}<PetShell><main className="pet-page"><PetBreadcrumb items={[{ name: "Pet Travel Bags" }]} />
    <section className="pet-collection-hero"><div><p className="eyebrow">Custom functional bag development</p><h1>Custom Pet Travel Bag Manufacturer</h1><p className="pet-lead">OEM and ODM pet carriers, travel organizers, backpacks and walking accessories developed for brands, retailers and distributors.</p><PetActions format="Pet Travel Bags Collection" secondary /><ul className="pet-highlight-list">{highlights.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="pet-banner-placeholder" role="img" aria-label="Category banner photography placeholder for custom pet travel bag collection"><span>Desktop 2400 × 1100 · Mobile 1200 × 1500</span><strong>Custom Pet Travel Bags for Private-Label Brands</strong><p>Approved collection photography pending</p></div></section>
    <section className="pet-trust-line" aria-label="Collection services">Sampling <span>•</span> Custom Materials <span>•</span> Private Label <span>•</span> Bulk Manufacturing</section>
    <section className="pet-section" id="categories"><div className="pet-heading"><div><p className="eyebrow">10 category paths</p><h2>Pet travel product categories</h2></div><p>Each route has a distinct buyer intent and links to relevant product development pages.</p></div><div className="pet-category-grid">{Object.entries(petCategories).map(([slug, category]) => <article key={slug}><p className="eyebrow">OEM / ODM category</p><h3><Link href={`${petCollectionUrl}${slug}/`}>{category.name}</Link></h3><p>{category.description}</p><Link className="pet-text-link" href={`${petCollectionUrl}${slug}/`}>Explore {category.name.toLowerCase()}</Link></article>)}</div></section>
    <section className="pet-section pet-muted"><div className="pet-heading"><div><p className="eyebrow">12 original programs</p><h2>Featured pet travel bags and accessories</h2></div><p>All concepts require product-specific samples and approved specifications; photography is listed as a remaining asset.</p></div><div className="pet-product-grid">{petProducts.map((product) => <PetProductCard key={product.code} product={product} />)}</div></section>
    <section className="pet-section"><div className="pet-heading"><div><p className="eyebrow">Why source from Cappuccino Bag?</p><h2>Functional-bag development for private-label buyers</h2></div><p>Pet travel bags extend the existing outdoor, sports, travel and functional bag manufacturing position.</p></div><div className="pet-reason-grid">{reasons.map(([heading, body]) => <article key={heading}><h3>{heading}</h3><p>{body}</p></article>)}</div></section>
    <section className="pet-section pet-dark"><div className="pet-heading"><div><p className="eyebrow">Materials and construction</p><h2>Build the specification around use, load and market</h2></div><p>Equivalent materials are reviewed against durability, documentation, hand feel, cost and availability.</p></div><div className="pet-material-grid">{materials.map(([heading, body]) => <article key={heading}><h3>{heading}</h3><p>{body}</p></article>)}</div></section>
    <section className="pet-section"><div className="pet-heading"><div><p className="eyebrow">Customization capabilities</p><h2>Dimensions, compartments, colors, logos and packaging</h2></div><p>Buyers can submit sketches, tech packs, reference images or samples. The brief should define intended pet or load, dimensions, functions, quantity, target market and target timeline.</p></div><div className="pet-answer-grid"><article><h3>Product engineering</h3><p>Pattern, ventilation, access, structure, base, carry system, pockets, tethers and attachment details are developed for the approved use.</p></article><article><h3>Brand system</h3><p>Stock or custom colors, printing, embroidery, woven labels, rubber patches, metal logos and branded pullers can be reviewed.</p></article><article><h3>Retail readiness</h3><p>Care labels, hangtags, barcode labels, paper wraps, cartons, gift packs and export carton marks can be coordinated.</p></article></div></section>
    <section className="pet-section pet-muted"><div className="pet-heading"><div><p className="eyebrow">Development process</p><h2>From brief to bulk manufacturing</h2></div><p>Sampling and production lead times are confirmed after design, material and order requirements are reviewed.</p></div><ol className="pet-process">{process.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></li>)}</ol></section>
    <section className="pet-section"><div className="pet-heading"><div><p className="eyebrow">Quality control</p><h2>Checks tied to the approved sample and specification</h2></div><p>Scope can include material review, first-piece confirmation, in-line workmanship, dimensions, seams, functions, logo placement, color, packing and carton marks. Project-specific tests are agreed before production.</p></div><div className="pet-answer-grid"><article><h3>Before production</h3><p>Confirm the approved sample, bill-of-material direction, color references, artwork, labels, packing and inspection criteria.</p></article><article><h3>During production</h3><p>Review incoming materials, first-piece construction and in-line workmanship against the agreed standard.</p></article><article><h3>Before shipment</h3><p>Complete final functional, visual, quantity, packing and carton-mark checks according to the order plan.</p></article></div></section>
    <section className="pet-section pet-sustainable"><div className="pet-heading"><div><p className="eyebrow">Sustainable material options</p><h2>Use documented inputs and precise claims</h2></div><p>Recycled shell, lining and webbing options, replaceable components and reduced-plastic packaging can be reviewed. GRS-certified material options are available subject to selected supplier documentation; finished-product certification is not implied.</p></div><Link className="pet-text-link" href="/recycled-material-bags/">Explore related recycled material guidance</Link></section>
    <section className="pet-section"><div className="pet-heading"><div><p className="eyebrow">Use cases</p><h2>One category, multiple commercial programs</h2></div><p>Formats can be coordinated by color, trim, labels and packaging without turning the wider website into a pet-products store.</p></div><div className="pet-use-grid">{useCases.map((use) => <span key={use}>{use}</span>)}</div></section>
    <section className="pet-section pet-muted"><div className="pet-heading"><div><p className="eyebrow">Answer-first buyer FAQ</p><h2>OEM/ODM pet travel bag questions</h2></div><p>Clear answers suitable for procurement teams and answer engines.</p></div><div className="pet-faq">{collectionFaqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    <section className="pet-section"><div className="pet-heading"><div><p className="eyebrow">Related functional bag categories</p><h2>Connect pet travel with the wider Cappuccino range</h2></div><p>Explore adjacent manufacturing capabilities without changing the site&apos;s core positioning.</p></div><div className="pet-context-links"><Link href="/custom-travel-backpacks-weekender-bags/">Travel bags</Link><Link href="/custom-outdoor-sports-travel-bags/">Outdoor bags</Link><Link href="/custom-hiking-daypacks-outdoor-backpacks/">Hiking bags</Link><Link href="/recycled-material-bags/">Sustainable materials</Link><Link href="/factory-trust-materials/">Factory proof</Link><Link href="/oem-odm-bag-manufacturer/">Custom manufacturing</Link><Link href="/pet-travel-guides/">Pet travel buyer guides</Link></div></section>
    <section className="pet-rfq"><div><p className="eyebrow">Quotation checklist</p><h2>Start your pet bag project</h2><p>Send the information below through the RFQ form, email info@cappuccinobag.net or WhatsApp +86 139 2871 5568.</p><QuotationChecklist /></div><PetActions format="Pet Travel Bags Collection" /></section>
  </main></PetShell></>;
}
