export const demoLeads = [
  {
    id: "demo-cap-001",
    customer_number: "DEMO-CAP-001",
    site: "cappuccinobag",
    company: "示例：Northwind Sports",
    name: "Alex Morgan",
    country: "United States",
    industry: "Sporting Goods",
    product_keywords: ["padel bag", "racket backpack"],
    source: "csv_demo",
    owner: "sales@example.com",
    stage: "qualified",
    score: 82,
    email: "buyer@example.invalid",
    whatsapp_phone: "+10000000000",
    next_follow_up: new Date(Date.now() + 86400000).toISOString(),
    created_at: new Date().toISOString(),
    is_demo: true,
  },
  {
    id: "demo-nov-001",
    customer_number: "DEMO-NOV-001",
    site: "novlane",
    company: "示例：Atelier Material Lab",
    name: "Sophie Lee",
    country: "France",
    industry: "Fashion Accessories",
    product_keywords: ["women handbag", "innovative material"],
    source: "manual_demo",
    owner: "sales@example.com",
    stage: "contacted",
    score: 74,
    email: "studio@example.invalid",
    whatsapp_phone: null,
    next_follow_up: new Date(Date.now() + 172800000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    is_demo: true,
  },
];

export const demoActivities = [
  { id: "demo-a1", title: "导入了 2 条示例线索", body: "仅在演示开关开启时显示", created_at: new Date().toISOString(), site: "cappuccinobag" },
  { id: "demo-a2", title: "生成英文 WhatsApp 草稿", body: "未自动发送", created_at: new Date(Date.now() - 3600000).toISOString(), site: "novlane" },
];
