import { runningArticles } from "./running-articles.js";
import { runningProducts } from "./running-data.js";
import { petArticles } from "./pet-travel-articles.js";
import { petCategories, petProducts } from "./pet-travel-data.js";
import { hybridProductEntries } from "./hybrid-padel-data.js";
import { hybridPadelArticles } from "./hybrid-padel-articles.js";
import { techGiftArticles, techGiftProductPath } from "./corporate-tech-gift-data.js";
import { cardHolderProducts } from "./card-holder-data.js";

const baseUrl = "https://www.cappuccinobag.com";

const routes = [
  { path: "/", priority: 1.0 },
  { path: "/custom-padel-bag-manufacturer", priority: 0.95 },
  { path: "/racket-sports/padel-bags", priority: 0.98, updated: "2026-08-12" },
  { path: "/products", priority: 0.9 },
  { path: "/corporate-tech-gift-solutions", priority: 0.92, updated: "2026-08-13" },
  { path: techGiftProductPath, priority: 0.95, updated: "2026-08-13" },
  { path: "/case-studies", priority: 0.86, updated: "2026-08-09" },
  { path: "/fletcher-hotels-custom-bag", priority: 0.84, updated: "2026-08-09" },
  { path: "/noeve-vegan-beauty-accessory", priority: 0.84, updated: "2026-08-09" },
  { path: "/kitty-couture-rhinestone-handbag", priority: 0.84, updated: "2026-08-09" },
  { path: "/inquiry", priority: 0.9 },
  { path: "/custom-pickleball-paddle-bags", priority: 0.9 },
  { path: "/custom-tennis-bag-manufacturer", priority: 0.9 },
  { path: "/custom-outdoor-sports-bag-manufacturer", priority: 0.88 },
  { path: "/custom-travel-backpacks-weekender-bags", priority: 0.88 },
  { path: "/outdoor-multifunctional-bag-manufacturing-guide", priority: 0.7 },
  { path: "/custom-tennis-bag-guide", priority: 0.7 },
  { path: "/pickleball-bag-customization-guide", priority: 0.7 },
  { path: "/hiking-backpack-customization-guide", priority: 0.68 },
  { path: "/quality-inspection-guide", priority: 0.65 },
  { path: "/moq-sampling-faq", priority: 0.65 },
  { path: "/contact/", priority: 0.9 },
  { path: "/privacy/", priority: 0.35 },
  { path: "/about-us/", priority: 0.9 },
  { path: "/faq/", priority: 0.86 },
  { path: "/blog/company-bio/", priority: 0.75 },
  { path: "/oem-odm-functional-bag-manufacturer-faq/", priority: 0.9 },
  { path: "/custom-tennis-padel-racket-bags/", priority: 0.95 },
  { path: "/custom-convertible-padel-backpack-duffel/", priority: 0.94 },
  { path: "/products/custom-padel-backpack-racket-compartment", priority: 0.94 },
  { path: "/products/premium-padel-racket-bag", priority: 0.94 },
  { path: "/products/custom-padel-duffel-bag-shoe-compartment", priority: 0.94 },
  { path: "/products/multi-functional-sports-backpack", priority: 0.94 },
  { path: "/padel-bags/custom-60l-padel-racket-duffel/", priority: 0.96 },
  { path: "/padel-bags/custom-30l-padel-backpack/", priority: 0.96 },
  { path: "/padel-accessories/", priority: 0.92 },
  { path: "/padel-accessories/custom-ventilated-padel-shoe-bag/", priority: 0.94 },
  { path: "/padel-accessories/custom-padel-organizer-pouch/", priority: 0.94 },
  { path: "/products/padel-work-tote-backpack-pdb001", priority: 0.97 },
  { path: "/padel-bags/hybrid-lifestyle-series-2026", priority: 0.97 },
  { path: "/blog/how-to-choose-office-to-court-padel-bag/", priority: 0.84 },
  { path: "/blog/multi-pocket-organization-padel-commuter-bag/", priority: 0.84 },
  { path: "/blog/recycled-water-resistant-fabrics-custom-padel-bags/", priority: 0.84 },
  { path: "/blog/one-lightweight-bag-office-to-padel-court/", priority: 0.82 },
  { path: "/running-waist-packs/", priority: 0.98 },
  { path: "/running/hydration-belts/", priority: 0.94 },
  { path: "/running/trail-running-belts/", priority: 0.94 },
  { path: "/running/marathon-race-belts/", priority: 0.94 },
  { path: "/running/phone-belts/", priority: 0.94 },
  { path: "/running/custom-oem-odm/", priority: 0.96 },
  { path: "/running-guides/", priority: 0.86 },
  { path: "/pet-travel-bags/", priority: 0.96 },
  { path: "/pet-travel-guides/", priority: 0.84 },
  { path: "/card-holders/", priority: 0.96, updated: "2026-08-09" },
  { path: "/rfid-card-holder-manufacturer/", priority: 0.94, updated: "2026-08-09" },
  { path: "/custom-leather-card-holder/", priority: 0.94, updated: "2026-08-09" },
  { path: "/custom-pickleball-paddle-bags/", priority: 0.95 },
  { path: "/custom-hiking-daypacks-outdoor-backpacks/", priority: 0.95 },
  { path: "/custom-waterproof-adventure-duffel/", priority: 0.92 },
  { path: "/custom-waterproof-wheeled-gear-bag/", priority: 0.92 },
  { path: "/custom-insulated-cooler-backpack/", priority: 0.92 },
  { path: "/custom-waterproof-roll-top-backpack/", priority: 0.92 },
  { path: "/custom-insulated-cooler-tote-bag/", priority: 0.92 },
  { path: "/custom-laptop-travel-backpack/", priority: 0.92 },
  { path: "/custom-rfid-wallet-manufacturer/", priority: 0.9 },
  { path: "/custom-magsafe-cardholder-manufacturer/", priority: 0.86 },
  { path: "/custom-phone-pouch-manufacturer/", priority: 0.86 },
  { path: "/phone-case-cardholder-gift-set-oem/", priority: 0.86 },
  { path: "/vegan-leather-tech-accessories-manufacturer/", priority: 0.86 },
  { path: "/custom-cardholder-manufacturer/", priority: 0.9 },
  { path: "/rfid-wallets-passport-holders/", priority: 0.88 },
  { path: "/hotel-group-custom-bag-project-guide/", priority: 0.88 },
  { path: "/custom-padel-bags.html", priority: 0.9 },
  { path: "/padel-brand-collection-development/", priority: 0.9 },
  { path: "/custom-pickleball-bags.html", priority: 0.9 },
  { path: "/custom-tennis-bags.html", priority: 0.9 },
  { path: "/custom-hiking-backpacks.html", priority: 0.9 },
  { path: "/custom-sports-duffel-bags.html", priority: 0.9 },
  { path: "/custom-hotel-bags.html", priority: 0.9 },
  { path: "/resources/outdoor-multifunctional-bag-manufacturing-guide/", priority: 0.78 },
  { path: "/resources/custom-tennis-bag-guide/", priority: 0.78 },
  { path: "/resources/pickleball-bag-customization-guide/", priority: 0.78 },
  { path: "/resources/hiking-backpack-customization-guide/", priority: 0.78 },
  { path: "/resources/quality-inspection-guide/", priority: 0.78 },
  { path: "/resources/moq-sampling-faq/", priority: 0.78 },
  { path: "/factory-trust-materials/", priority: 0.82 },
  { path: "/recycled-material-bags/", priority: 0.84 },
  { path: "/oem-odm-bag-manufacturer/", priority: 0.9 },
  { path: "/alcantara-collection/", priority: 0.94 },
  { path: "/custom-alcantara-duffle-bag/", priority: 0.92 },
  { path: "/custom-alcantara-iphone-case/", priority: 0.9 },
  { path: "/custom-alcantara-card-holder/", priority: 0.9 },
  { path: "/blog/alcantara-bag-accessory-production-process/", priority: 0.84 },
  { path: "/blog/how-to-source-custom-waterproof-roll-top-backpack/", priority: 0.84 },
  { path: "/blog/custom-cooler-tote-bag-development-guide/", priority: 0.84 },
  { path: "/blog/laptop-travel-backpack-oem-buying-guide/", priority: 0.84 },
  { path: "/blog/verify-custom-bag-manufacturer-china/", priority: 0.84 },
  { path: "/blog/custom-bag-development-quality-control-process/", priority: 0.84 },
  { path: "/blog/bag-manufacturer-compliance-documents-explained/", priority: 0.84 },
];

export default function sitemap() {
  const dynamicRoutes = [
    ...hybridProductEntries.map((product) => ({ path: `/products/${product.slug}`, priority: 0.95 })),
    ...Object.keys(hybridPadelArticles).map((slug) => ({ path: `/blog/${slug}`, priority: 0.84 })),
    ...Object.keys(techGiftArticles).map((slug) => ({ path: `/blog/${slug}`, priority: 0.84, updated: "2026-08-13" })),
    ...runningProducts.map((product) => ({ path: product.href, priority: 0.9 })),
    ...runningArticles.map((article) => ({ path: `/running-guides/${article.slug}/`, priority: 0.84 })),
    ...Object.keys(petCategories).map((slug) => ({ path: `/pet-travel-bags/${slug}/`, priority: 0.9 })),
    ...petProducts.map((product) => ({ path: product.href, priority: 0.92 })),
    ...petArticles.map((article) => ({ path: `/pet-travel-guides/${article.slug}/`, priority: 0.82 })),
    ...cardHolderProducts.map((product) => ({ path: product.href, priority: 0.92, updated: "2026-08-09" })),
  ];
  const redirectedPaths = new Set([
    "/custom-padel-bags.html",
    "/custom-pickleball-bags.html",
    "/custom-pickleball-bag-manufacturer",
    "/custom-tennis-bags.html",
    "/custom-hiking-backpacks.html",
    "/custom-hiking-backpack-manufacturer",
    "/custom-hiking-daypacks-outdoor-backpacks",
    "/custom-travel-bag-luggage-manufacturer",
    "/rfq",
    "/custom-convertible-padel-backpack-duffel",
    "/resources/outdoor-multifunctional-bag-manufacturing-guide",
    "/resources/custom-tennis-bag-guide",
    "/resources/pickleball-bag-customization-guide",
    "/resources/hiking-backpack-customization-guide",
    "/resources/quality-inspection-guide",
    "/resources/moq-sampling-faq",
    "/custom-sports-duffel-bags.html",
    "/custom-hotel-bags.html",
  ]);
  const priorityOverrides = new Map([
    ["/racket-sports/padel-bags", 0.98],
    ["/custom-padel-bag-manufacturer", 0.95],
    ["/inquiry", 0.9],
    ["/custom-pickleball-paddle-bags", 0.9],
    ["/custom-tennis-bag-manufacturer", 0.9],
    ["/custom-outdoor-sports-bag-manufacturer", 0.88],
    ["/custom-travel-backpacks-weekender-bags", 0.88],
    ["/running-waist-packs", 0.82],
    ["/pet-travel-bags", 0.78],
  ]);
  const unique = new Map();
  for (const route of [...routes, ...dynamicRoutes]) {
    const path = route.path === "/" ? "/" : route.path.replace(/\/+$/, "");
    if (redirectedPaths.has(path) || path.startsWith("/crm") || path.startsWith("/api")) continue;
    const isProduct = path.startsWith("/products/") || path.startsWith("/padel-bags/") || path.startsWith("/padel-accessories/");
    unique.set(path, {
      url: `${baseUrl}${path}`,
      lastModified: route.updated || "2026-08-02",
      changeFrequency: "weekly",
      priority: priorityOverrides.get(path) || (isProduct ? Math.min(route.priority, 0.85) : route.priority),
    });
  }
  return [...unique.values()];
}
