import { runningArticles } from "./running-articles";
import { runningProducts } from "./running-data";
import { petArticles } from "./pet-travel-articles";
import { petCategories, petProducts } from "./pet-travel-data";

const baseUrl = "https://www.cappuccinobag.com";

const routes = [
  { path: "/", priority: 1.0 },
  { path: "/inquiry/", priority: 0.95 },
  { path: "/contact/", priority: 0.9 },
  { path: "/privacy/", priority: 0.35 },
  { path: "/about-us/", priority: 0.9 },
  { path: "/faq/", priority: 0.86 },
  { path: "/blog/company-bio/", priority: 0.75 },
  { path: "/oem-odm-functional-bag-manufacturer-faq/", priority: 0.9 },
  { path: "/custom-tennis-padel-racket-bags/", priority: 0.95 },
  { path: "/custom-convertible-padel-backpack-duffel/", priority: 0.94 },
  { path: "/products/custom-padel-backpack-racket-compartment", priority: 0.94 },
  { path: "/products/premium-padel-racket-bag", priority: 0.94 },
  { path: "/products/custom-padel-duffel-bag-shoe-compartment", priority: 0.94 },
  { path: "/products/multi-functional-sports-backpack", priority: 0.94 },
  { path: "/padel-bags/custom-60l-padel-racket-duffel/", priority: 0.96 },
  { path: "/padel-bags/custom-30l-padel-backpack/", priority: 0.96 },
  { path: "/padel-accessories/", priority: 0.92 },
  { path: "/padel-accessories/custom-ventilated-padel-shoe-bag/", priority: 0.94 },
  { path: "/padel-accessories/custom-padel-organizer-pouch/", priority: 0.94 },
  { path: "/running-waist-packs/", priority: 0.98 },
  { path: "/running/hydration-belts/", priority: 0.94 },
  { path: "/running/trail-running-belts/", priority: 0.94 },
  { path: "/running/marathon-race-belts/", priority: 0.94 },
  { path: "/running/phone-belts/", priority: 0.94 },
  { path: "/running/custom-oem-odm/", priority: 0.96 },
  { path: "/running-guides/", priority: 0.86 },
  { path: "/pet-travel-bags/", priority: 0.96 },
  { path: "/pet-travel-guides/", priority: 0.84 },
  { path: "/custom-pickleball-paddle-bags/", priority: 0.95 },
  { path: "/custom-hiking-daypacks-outdoor-backpacks/", priority: 0.95 },
  { path: "/custom-waterproof-adventure-duffel/", priority: 0.92 },
  { path: "/custom-waterproof-wheeled-gear-bag/", priority: 0.92 },
  { path: "/custom-insulated-cooler-backpack/", priority: 0.92 },
  { path: "/custom-waterproof-roll-top-backpack/", priority: 0.92 },
  { path: "/custom-insulated-cooler-tote-bag/", priority: 0.92 },
  { path: "/custom-laptop-travel-backpack/", priority: 0.92 },
  { path: "/custom-rfid-wallet-manufacturer/", priority: 0.9 },
  { path: "/custom-magsafe-cardholder-manufacturer/", priority: 0.86 },
  { path: "/custom-phone-pouch-manufacturer/", priority: 0.86 },
  { path: "/phone-case-cardholder-gift-set-oem/", priority: 0.86 },
  { path: "/vegan-leather-tech-accessories-manufacturer/", priority: 0.86 },
  { path: "/custom-cardholder-manufacturer/", priority: 0.9 },
  { path: "/rfid-wallets-passport-holders/", priority: 0.88 },
  { path: "/hotel-group-custom-bag-project-guide/", priority: 0.88 },
  { path: "/custom-padel-bags.html", priority: 0.9 },
  { path: "/padel-brand-collection-development/", priority: 0.9 },
  { path: "/custom-pickleball-bags.html", priority: 0.9 },
  { path: "/custom-tennis-bags.html", priority: 0.9 },
  { path: "/custom-hiking-backpacks.html", priority: 0.9 },
  { path: "/custom-sports-duffel-bags.html", priority: 0.9 },
  { path: "/custom-hotel-bags.html", priority: 0.9 },
  { path: "/resources/outdoor-multifunctional-bag-manufacturing-guide/", priority: 0.78 },
  { path: "/resources/custom-tennis-bag-guide/", priority: 0.78 },
  { path: "/resources/pickleball-bag-customization-guide/", priority: 0.78 },
  { path: "/resources/hiking-backpack-customization-guide/", priority: 0.78 },
  { path: "/resources/quality-inspection-guide/", priority: 0.78 },
  { path: "/resources/moq-sampling-faq/", priority: 0.78 },
  { path: "/factory-trust-materials/", priority: 0.82 },
  { path: "/recycled-material-bags/", priority: 0.84 },
  { path: "/oem-odm-bag-manufacturer/", priority: 0.9 },
  { path: "/alcantara-collection/", priority: 0.94 },
  { path: "/custom-alcantara-duffle-bag/", priority: 0.92 },
  { path: "/custom-alcantara-iphone-case/", priority: 0.9 },
  { path: "/custom-alcantara-card-holder/", priority: 0.9 },
  { path: "/blog/alcantara-bag-accessory-production-process/", priority: 0.84 },
  { path: "/blog/how-to-source-custom-waterproof-roll-top-backpack/", priority: 0.84 },
  { path: "/blog/custom-cooler-tote-bag-development-guide/", priority: 0.84 },
  { path: "/blog/laptop-travel-backpack-oem-buying-guide/", priority: 0.84 },
  { path: "/blog/verify-custom-bag-manufacturer-china/", priority: 0.84 },
  { path: "/blog/custom-bag-development-quality-control-process/", priority: 0.84 },
  { path: "/blog/bag-manufacturer-compliance-documents-explained/", priority: 0.84 },
];

export default function sitemap() {
  const dynamicRoutes = [
    ...runningProducts.map((product) => ({ path: product.href, priority: 0.9 })),
    ...runningArticles.map((article) => ({ path: `/running-guides/${article.slug}/`, priority: 0.84 })),
    ...Object.keys(petCategories).map((slug) => ({ path: `/pet-travel-bags/${slug}/`, priority: 0.9 })),
    ...petProducts.map((product) => ({ path: product.href, priority: 0.92 })),
    ...petArticles.map((article) => ({ path: `/pet-travel-guides/${article.slug}/`, priority: 0.82 })),
  ];
  return [...routes, ...dynamicRoutes].map((route) => ({
    url: `${baseUrl}${route.path}`,
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: route.priority,
  }));
}
